# Generated by Django 2.0.6 on 2019-03-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCRUDApp', '0002_auto_20190308_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesellmodel',
            name='imageURL',
            field=models.CharField(default='', max_length=500),
        ),
    ]
